### ISSUE TITLE
Zoom list text color

### ISSUE THREAD

**Issue by Korb** [winghongchan/dark-docs#10]
![2022-10-13_15-15-09](https://user-images.githubusercontent.com/3509797/195594321-0d8e6c98-eca0-44d7-9408-d19d3f388e56.png)

Dark Docs 2022.8.12, Mozilla Firefox 105.0.3 (64-bit), Microsoft Windows 10.0.19044.2130.

**Comment by winghongchan** [comment]
`v2022.10.20` has been released with a fix to this issue. 
If this issue has been resolved on your computer, you may close this issue.
