### ISSUE TITLE
Non-contrasting message text to the user when sharing a document

### ISSUE THREAD

**Issue by Korb** [winghongchan/dark-docs#11]
![2022-10-26_10-41-15](https://user-images.githubusercontent.com/3509797/197964844-e02c7501-39af-4120-bdb1-3cd0528564c2.png)

Mozilla Firefox 106.0.1 (64-bit)
Stylus 1.5.26 (30 August 2022)
Dark Docs 2022.10.20

**Comment by winghongchan** [comment]
Version 2022.10.27 has been released to userstyles.world with a fix to this issue. Further refinements to the share dialog will be made in the coming weeks. You may now close this issue if it appears to be resolved on your end.
