### ISSUE TITLE
Lighter background?

### ISSUE THREAD

**Issue by paul1149** [winghongchan/dark-docs#13]
An amazing piece of work!

The problem I have is that too much contrast hurts my eyes. I would like to make the background color of the paper lighter than the current near-black. Is there some way to achieve this? I tried messing with the "canvas" selector but got nowhere.

Thanks much.

**Comment by winghongchan** [comment]
Version 2022.11.16 has been released with a "Document contrast while inverted" setting. Open the Stylus extension popup, click on the gear next to "Dark Docs", and change the number next to the setting. Reduce the number to reduce contrast. 

![image](https://user-images.githubusercontent.com/64437199/202300761-55e06425-ba03-4e66-83db-31034c32fe1c.png)

**Comment by paul1149** [comment]
EXCELLENT! Thanks so much for that, and for doing it so quickly. Much appreciated. The more subtle scheme looks great.
