### ISSUE TITLE
"Notify people" mesage text color

### ISSUE THREAD

**Issue by Korb** [winghongchan/dark-docs#14]
The text is too dark.

![2022-12-09_09-19-40](https://user-images.githubusercontent.com/3509797/206638029-a31eca34-195c-4953-b246-72c7d4758f43.png)

> Foreground: #3C4043
> Background: #202124
> The contrast ratio is: 1.5:1
> 1.4.3 Contrast (Minimum) (AA) — Fail for large and regular text
> 1.4.6 Contrast (Enhanced) (AAA) — Fail for large and regular text
> 1.4.11 Non-text Contrast (AA) — Fail for UI components and graphical objects

**Comment by winghongchan** [comment]
Version 2022.12.17 has been released with many fixes to the share dialog, including the contrast issue you have pointed out here.
