### ISSUE TITLE
Document outline background color

### ISSUE THREAD

**Issue by Korb** [winghongchan/dark-docs#15]
Without Dark Docs 2022.12.17:
![2023-01-04_18-32-57](https://user-images.githubusercontent.com/3509797/210590890-86224747-a72a-444a-b753-37de900913f7.png)
With Dark Docs 2022.12.17:
![2023-01-04_18-32-02](https://user-images.githubusercontent.com/3509797/210590895-065d5286-0bf6-4b11-ac06-318ed369b0de.png)
Mozilla Firefox 109.0b7 (64-bit), Stylus 1.5.26 (1 September 2022)

**Comment by winghongchan** [comment]
Dark Docs v2023.01.17 has been released with a fix to this. 

I reproduced this issue by setting a document to pageless mode, opening the print preview, and closing the print preview. If the issue persists on your computer, please let me know how you produced it. 

If the issue has been solved, you make close this issue.
