### ISSUE TITLE
Google’s Material U-ification breaks a lot of things

### ISSUE THREAD

**Issue by winghongchan** [winghongchan/dark-docs#16]
Whelp. Google has Material U’d Google Docs so Dark Docs will be in repair for the next little while. 
Dark Docs was always trying to look like what Google would do themselves. So, Dark Docs after the repair will use Material U as well (perhaps with several consistency fixes since Google appears to be having trouble re-implementing everything with Material U).

Android 12-like dynamic colour shouldn’t be too hard but you would have to go to https://m3.material.io/theme-builder#/custom to download the colour palette since I don’t think I can use CSS alone to generate colour palettes. 

![image](https://user-images.githubusercontent.com/64437199/225476572-c3da7c7f-351d-4e19-984c-85779403a6f6.png)

**Comment by winghongchan** [comment]
well guess what! It’s not class names that keep changing. It’s the Material You colour system!

Last time I checked:
![](https://lh3.googleusercontent.com/VW4oN7eUaOM0lFAc10Xleb2mjBtBNG7adt8sCHE5AZkrV9Rbjua-zgJ8lrWsAjbtVJ76vZByuKiNfWDCnoOIhjQYGmI92629mRh41f2-2a8=s0)

Now:
![](https://lh3.googleusercontent.com/5gVDi0Ujx_vZUiEsAogDo1pASdkZycOX5UQdXGbfoxl9ixT3RY2ca6KJg623bw7OgIgGvjEVQK4EbMvIZftKG7EmGLrZTOu_DexYnWZAXg=s0)

It seems like the _new_ Material You leaves more flexibility to me so I will be adopting it (also this way I have some documentation to reference). This will take some time as I redo the CSS variables.

**Comment by AvgZing** [comment]
Is thete any potential that you'll adapt this to other sites in the drive workspace? If not, what's the easiest way to do it ourselves? Slides and Drive itself have beem U-ified as well and my other styles have broke, and it's a nightmare to sort through their new hundreds of variables

**Comment by winghongchan** [comment]
Dark Docs is licensed under the GPLv3 so you could fork it and make something for Google Sheets and Slides. I don’t use Google Sheets so I won’t be making a dark mode for that soon. A dark mode for Google Slides is more likely. 

Drive is different because it uses CSS variables for colours so it’s easier to make a new theme for it. They are named to match the new [Material You colour tokens](https://m3.material.io/styles/color/the-color-system/tokens) so you can get a lot done just by assigning new values to the CSS variables Drive already uses.

**Comment by winghongchan** [comment]
Ok I think Dark Docs is pretty good now but of course if you come across any issues please report them by making a new issue. As for myself, I will begin work on Shades and Slides (the name might be changed…), a dark mode for Google Slides in the same Googley style as Dark Docs.
