### ISSUE TITLE
Top bar becomes light after scrolling down in Viewing mode

### ISSUE THREAD

**Issue by checkraisefold** [winghongchan/dark-docs#17]
Tin.
![image](https://user-images.githubusercontent.com/19525688/229331295-eeca7309-8d98-402b-b394-51649d390293.png)
After scrolling down at all:
![image](https://user-images.githubusercontent.com/19525688/229331300-98784425-3e58-4861-ba16-60adf87d9a9c.png)

**Comment by checkraisefold** [comment]
Scrolling down adds this to the element:
![image](https://user-images.githubusercontent.com/19525688/229331343-59366b22-bd72-4988-938e-d150046fd148.png)
Becomes dark again after disabling this with dev tools.

**Comment by checkraisefold** [comment]
Works fine after adding !important to docs-hub-chrome top bar selector for background and border-bottom-color and docs-titlebar-buttons selector background-color.

**Comment by winghongchan** [comment]
Dark Docs v2023.04.05 has been released with a fix to this issue.\
You may close this issue the issue has been fixed for your system.
 
![image](https://user-images.githubusercontent.com/64437199/230092132-36655d4d-ec19-49d5-8037-ce57c3be2ca9.png)

**Comment by checkraisefold** [comment]
Hmm, is topbar still changing color to be slightly lighter an intentional design decision?

**Comment by winghongchan** [comment]
Yes, it’s meant to change colour like that. Google Docs in light mode does that too — it’s Google’s way of showing the user that the top bar is elevated above the rest of the interface since they removed most shadows in Material You (M3).

**Comment by checkraisefold** [comment]
Cool, this is fixed then.
