### ISSUE TITLE
"Borders and shading" window text color

### ISSUE THREAD

**Issue by Korb** [winghongchan/dark-docs#19]
Dark Docs 2023.04.10:
![Screenshot_2023-04-11_10-20-33](https://user-images.githubusercontent.com/3509797/231085715-d8cd4c4e-a23f-4295-8523-007d9e771fed.png)

Without Dark Docs:
![Screenshot_2023-04-11_10-20-47](https://user-images.githubusercontent.com/3509797/231085754-4fafcd08-98de-4520-898a-bd167cecc594.png)

**Comment by winghongchan** [comment]
Dark Docs v2023.04.11 has been released with fixes for the Borders and shading dialog and more. If the issue has been resolved on your system, you may close this issue.

**Comment by Korb** [comment]
@winghongchan, broken again:

![2024-12-10_18-40-03](https://github.com/user-attachments/assets/bc1ec897-a008-4f61-9c3b-050e82099518)

**Comment by winghongchan** [comment]
Dark Docs v2024.12.21 has been released with a fix for this issue and others. Please try it out, and close this issue if it looks okay now.
