### ISSUE TITLE
[bug] "Sorry, unable to open the file at present" screen

### ISSUE THREAD

**Issue by Korb** [winghongchan/dark-docs#26]
On the next screen, some of the text is unreadable:

![Screenshot 2023-12-25 at 11-37-23 Page not found](https://github.com/winghongchan/dark-docs/assets/3509797/a4ae72af-ff5a-4fa1-af74-17f1ea685195)

> Sorry, unable to open the file at present. Please check the address and try again.

Mozilla Firefox 121.0 (64-bit)
Dark Docs 2023.12.08

**Comment by winghongchan** [comment]
I’ve never encountered the “Sorry, unable to open the file at present” screen before. How do you make it appear?

**Comment by Korb** [comment]
Open a link to a document that you do not even have access to view.

**Comment by winghongchan** [comment]
Dark Docs v2024.01.31 has been released to address error pages such as “Page Not Found” and “Access Denied”. If the issue has been resolved you may now close this issue.
