### ISSUE TITLE
"Borders and shading" Position and Border dash

### ISSUE THREAD

**Issue by Korb** [winghongchan/dark-docs#29]
![2024-11-14_10-13-43](https://github.com/user-attachments/assets/61eeb698-374a-42c8-bdbb-199d3ad7ea80)

Dark Docs 2024.10.29
Stylus 1.5.51 (August 22, 2024)
Mozilla Firefox 133.0b8 (64-bit)

**Comment by winghongchan** [comment]
Dark Docs v2024.11.28 has been released to address this bug. If it’s fixed on your computer, you may close this issue.
