### ISSUE TITLE
The `Add shortcut to Drive?` window is displayed in light theme

### ISSUE THREAD

**Issue by Korb** [winghongchan/dark-docs#30]
![Screenshot 2024-12-10 at 18-48-47 Streisand (RIP) - Google Docs](https://github.com/user-attachments/assets/53ea3d0a-1546-4062-b6c2-fcb8d40e51af)

Dark Docs 2024.11.28
Stylus 1.5.51 (August 22, 2024)
Mozilla Firefox 134.0b8 (64-bit)

**Comment by winghongchan** [comment]
Dark Docs v2024.12.21 has been released with a fix for this issue and others. Please try it out, and close this issue if it looks okay now.
