### ISSUE TITLE
Check mark of the selected document language

### ISSUE THREAD

**Issue by Korb** [winghongchan/dark-docs#7]
...is almost indistinguishable:

![2022-05-16_17-42-19](https://user-images.githubusercontent.com/3509797/168619340-8ef70ae5-487e-4a6d-a55a-5195ccd3ada7.png)

**Comment by winghongchan** [comment]
This should be fixed by version 2022.7.27 (available at [https://userstyles.world/style/2597](https://userstyles.world/style/2597)). Please report back to tell me if this is fixed for you.

**Comment by Korb** [comment]
Dark Docs 2023.02.14:
![2023-02-19_13-25-03](https://user-images.githubusercontent.com/3509797/219942352-c3dbd70a-3b1c-4e63-888a-8065938d2723.png)
