### ISSUE TITLE
Stylus failed to parse usercss:

### ISSUE THREAD

**Issue by redrios** [winghongchan/dark-docs#9]
clicking on install (i has stylus on opera gx) i get tab with loading... on the title and
Stylus failed to parse usercss:
Invalid version number. The value doesn't match SemVer pattern: 2022.07.25
as the header, underlining the version date in bluish
cant install it thus

**Comment by winghongchan** [comment]
Sorry about that — I did not understand semantic versioning (nor was I interested as Dark Docs doesn’t really have an API). However, the latest release, 2022.7.27 should have fixed this. Please report back to tell me if you can now install it.
